#################################################################
#################################################################
##                                                             ##
##                                                             ##
## Andrea Grandieri andreagrandieri.github.io                  ##
##                                                             ##
##                                                             ##
#################################################################
#################################################################

# show_downloads: true is not implemented for this theme

# Title propagated to the entire site, but within the domain (with consideration of subdomains)
title: MagicMirror-GBM

#################################################################

# Path to the logo to be used in the site
# # logo: "PATH"

#################################################################

# AUX LINKS
# Aux links are placed in the upper right corner of the site and are essentially simple links
# Aux links for the upper right navigation
# The last entry of this list appears on the far right
# Links as: "javascript:***" are not compatible with the "aux_links_new_tab" option set to true
aux_links:
  "<i class=\"fa-solid fa-down-long fa-3x\"></i> <div class=\"fs-5\">ZIP</div>":
    - https://github.com/AndreaGrandieri/MagicMirror-GBM/zipball/main
  "<i class=\"fa-solid fa-down-long fa-3x\"></i> <div class=\"fs-5\">TAR</div>":
    - https://github.com/AndreaGrandieri/MagicMirror-GBM/tarball/main
  "<i class=\"fa-brands fa-github fa-3x\"></i>":
    - "https://github.com/AndreaGrandieri/MagicMirror-GBM"
  # # "<div id=\"lightdarkSwitcherButton\"><i class=\"fa-solid fa-moon fa-3x\"></i></div>":
  # #   - "javascript:themeModeSwitcher();"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

#################################################################

# Specificy the baseurl for the site
# Example: looking at: "andreagrandieri.github.io/MagicMirror-GBM" set baseurl: "MagicMirror-GBM"
# Example: looking at: "andreagrandieri.github.io" do not specify a baseurl; "" will be the default
baseurl: MagicMirror-GBM
