theme: jekyll-theme-tactile
show_downloads: true

github:
  zip_url: javascript:getLatestRelease(`https://api.github.com/repos/AndreaGrandieri/MagicMirror-GBM/releases/latest`, `zip`)
  tar_url: javascript:getLatestRelease(`https://api.github.com/repos/AndreaGrandieri/MagicMirror-GBM/releases/latest`, `tar`)
