name: acqua

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write  

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: bundle
        working-directory: docsite
      
  second:
    runs-on: ubuntu-latest
    steps:
      - run: bundle exec jekyll build
        working-directory: docsite
