#################################################################
#################################################################
##                                                             ##
##                                                             ##
## Andrea Grandieri andreagrandieri.github.io                  ##
##                                                             ##
##                                                             ##
#################################################################
#################################################################

# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

defaults:
  run:
    working-directory: ./docsite

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Disregards "default working-directory" set above, because it is not needed here
      - name: Checkout
        uses: actions/checkout@v3
      # Disregards "default working-directory" set above. Due to this, the "bundle install" command will be skipped
      - name: Setup Ruby
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          # runs 'bundle install' and caches installed gems automatically
          # Setting to false will skip the command "bundle install". Should be put to false since "bundle install" is run in the next step
          bundler-cache: false
      # Regards "default working-directory" set above
      - name: Run bundle install
        # There's no point in running "bundle cache": the GitHub Action's runner gets destroyed after the workflow is done. Thus, no cache will be used
        run: bundle install
      # Disregards "default working-directory" set above, because it is not needed here
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v2
        with:
          path: ./docsite
      # Regards "default working-directory" set above
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      # Disregards "default working-directory" set above. Due to this, the option "with path" is used
      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docsite

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
